export const MENU = {
    REGISTER_NODE: 'Register node',
    UPDATE_NODE: 'Update node',
    SET_NODE_TOKEN: 'Set node token',
    ADD_NODE_TOKEN: 'Add node token',
    REDUCE_NODE_TOKEN: 'Reduce node token',
    ADD_NAMESPACE: 'Add namespace',
    DISABLE_NAMESPACE: 'Disable namespace',
    ENABLE_NAMESPACE: 'Enable namespace',
    ADD_SERVICE: 'Add service',
    UPDATE_SERVICE: 'Update service',
    DISABLE_SERVICE: 'Disable service',
    ENABLE_SERVICE: 'Enable service',
    APPROVE_SERVICE: 'Approve service',
    DISABLE_SERVICE_DESTINATION: 'Disable service destination',
    ENABLE_SERVICE_DESTINATION: 'Enable service destination',
    REGISTER_VALIDATOR: 'Register validator',
    INIT_NDID: 'Init NDID',
    SET_TIMEOUT_BLOCK: 'Set timeout block register MQ destination'
}
